USE sql10728873;

DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS rel_Users_Actions;
DROP TABLE IF EXISTS Actions;
DROP TABLE IF EXISTS rel_Users_Tasks;
DROP TABLE IF EXISTS Relation_types;
DROP TABLE IF EXISTS rel_Groups_Employees;
DROP TABLE IF EXISTS rel_Groups_Tasks;
DROP TABLE IF EXISTS rel_Areas_Tasks;
DROP TABLE IF EXISTS Task;
DROP TABLE IF EXISTS Status_task;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Status_employee;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Areas;
DROP TABLE IF EXISTS Status_area;
DROP TABLE IF EXISTS Status_group;
